# These are overridden in the site hugo.toml
baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

# default menu contents
# add extras through page front matter
# this splits defaults from featuring
# menus = ['main']
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
