name = 'Hugo-a-GoGo'
license = 'MIT'
licenselink = 'https://github.com/jackokring/hugo-a-gogo/LICENSE'
description = 'K Ring Technologies Theme Demo'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/jackokring/hugo-a-gogo'

# If you have a running demo of the theme
#demosite = 'https://owner.github.io/repo'

# Taxonomy terms
#tags = ['blog', 'company']
#features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Simon Jackson'
  homepage = 'https://kring.co.uk'
