baseURL = 'https://kring.co.uk/'
languageCode = 'en-GB'
title = 'K Ring Technologies Ltd'
#theme = 'hugo-a-gogo'

# default menu contents
# add extras through page front matter
# this splits defaults from featuring
# menus = ['main']
[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[taxonomies]
tag = 'tags'
[markup]
[markup.goldmark.parser.attribute]
block = true
title = true
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
[markup.highlight]
# override with syntax.css
noClasses = false
#    style = 'monokai'
lineNos = true
#    lineNos = false
[params]
math = false
