session_name: elm
windows:
- layout: b242,193x41,0,0,5
  options:
    '@tmux_window_name_enabled': 0
  panes:
  - focus: 'true'
    shell_command: htop
  start_directory: /home/jacko
  window_name: htop
- focus: 'true'
  layout: adc3,192x40,0,0,6
  options:
    '@tmux_window_name_enabled': 1
  panes:
  - pane
  start_directory: /home/jacko/projects/elm
  window_name: espeak-ng What are y
